import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {

  
  return (
    <div>
      <Head>
        <title>Fluid Level Detector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;700&display=swap" rel="stylesheet" />
      </Head>
      
    </div>
  )
}

export default Home
